--- 
- hosts: all
  remote_user: root
  become: yes
  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "8080" 
    jenkins_plugins:
      - ansicolor

  roles: 
    - geerlingguy.firewall 
    - geerlingguy.ansible 
    - geerlingguy.java
    - geerlingguy.jenkins

  tasks:
    - name: Copy file main.yml to /opt/ansible-for-devops/ directory on the VM
      ansible.builtin.copy: 
        src: main.yml
        dest: /opt/ansible-for-devops/
        owner: root
        group: root
      tags: copy-file      